---
rewards:
  8dfd50fa-8df8-497e-8f00-581306625691:
    name: Замедление
    action: effect
    effect:
      id: slow
      duration: 600 # SECONDS*20
      amplifier: 2
options:
  useDisplayName: true
players:
  - Estintax:antoshka55
strings:
  prefix: "§a[TTVRewards]§f "
  receive_reward: "{name} получил награду §6{reward_name}"
  receive_message: "Пожелание: §b{message}"
  connected: "Вы подключены к чату §3{channel}"
  err_missarg: "§c[Ошибка] §6{reward_name} не содержит нужных параметров"
  err_unknownmob: "§c[Ошибка]§f Существо с именем §3{mob_name}§f не существует"