---
rewards:
  8dfd50fa-8df8-497e-8f00-581306625691:
    name: Замедление
    action: effect
    effect:
      id: slow
      duration: 60
      amplifier: 2
options:
  useDisplayName: true
players:
  - Estintax:antoshka55
strings:
  prefix: "§a[TTVRewards]§f "
  receive_reward: "{name} получил награду §6{reward_name}"
  receive_message: "Пожелание: §b{message}"
  connected: "Вы подключены к чату §3{channel}"
  kill: "Убийство"
