---
rewards:
  8dfd50fa-8df8-497e-8f00-581306625691:
    name: Slowness
    action: effect
    effect:
      id: slow
      duration: 600 # SECONDS*20
      amplifier: 2
options:
  useDisplayName: true
players:
  - Estintax:antoshka55
strings:
  prefix: "§a[TTVRewards]§f "
  receive_reward: "{name} receive an reward §6{reward_name}"
  receive_message: "Message: §b{message}"
  connected: "You are connected to the §3{channel}"
  err_missaction: "§c[Error]§f The reward §6{reward_name}§f does not specify an action"
  err_missarg: "§c[Error] §6{reward_name}§f does not contain the necessary parameters"
  err_unknownaction: "§c[Error]§f The action in the award §6{reward_name}§f does not exist"
  err_unknownmob: "§c[Error]§f A creature named §3{mob_name}§f does not exist"
  err_unknownitem: "§c[Error]§f Item §3{item_name}§f does not exist"
  err_unknownsound: "§c[Error]§f Sound §3{sound_name}§f does not exists"
  err_wrongworld: "§c[Error]§f World §3{world_name}§f does not exist"
  err_wrongeffect: "§c[Error]§f Effect §3{effect_name}§f does not exist"
  warn_netherfound: "§6[Warning] §fJump is disabled in nether"
  cmd_usage: "Usage: /ttvrewards [reload|about]"
  cmd_usage_reload: " reload - reloads the configuration"
  cmd_usage_about: " about - brief information about the plugin"
  cmd_usage_test: " test - reward testing"
  cmd_usage_test_in: "Usage: /ttvrewards test <channel> <reward ID>"
  cmd_version: "Version: "
  cmd_author: "Author: "
  cmd_description: "Description: "
  cmd_reloaded: "The configuration file is reloaded"
  cmd_test_execute: "Calling the reward handler..."
