name: TTVRewards
main: in.pinig.ttvrewards.Main
description: Use channel points rewards to interact with MC world
version: "0.1"
author: Estintax
commands:
  ttvrewards:
    description: Various sub-commands for managing TTVRewards
    usage: /ttvrewards [reload|about]